# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: fc2json 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "fc2json"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Roberto Pepato"]
  s.date = "2013-12-30"
  s.description = "fc2json queries, downloads and formats all data from a remote Esri feature service, exposing it as json representation"
  s.email = "rpepato@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/fc2json.rb",
    "spec/fc2json_spec.rb",
    "spec/fixtures/vcr_cassettes/1000_batch_size.yml",
    "spec/fixtures/vcr_cassettes/3000_batch_size.yml",
    "spec/fixtures/vcr_cassettes/3_batch_size.yml",
    "spec/fixtures/vcr_cassettes/4_batch_size.yml",
    "spec/fixtures/vcr_cassettes/6_batch_size.yml",
    "spec/fixtures/vcr_cassettes/empty.yml",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/rpepato/fc2json"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.0.rc.1"
  s.summary = "Converts Esri feature services to Json"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.5.10"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0", "~> 2.8"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.7", "~> 1.8"])
    else
      s.add_dependency(%q<nokogiri>, ["~> 1.5.10"])
      s.add_dependency(%q<rspec>, [">= 2.8.0", "~> 2.8"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.7", "~> 1.8"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["~> 1.5.10"])
    s.add_dependency(%q<rspec>, [">= 2.8.0", "~> 2.8"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.7", "~> 1.8"])
  end
end

